// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */

const VERSION = 1
import { c } from 'hyperschema/runtime'

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @hyperdb-example/user
const encoding0 = {
  preencode (state, m) {
    c.uint8.preencode(state, m.id)
    c.string.preencode(state, m.name)
  },
  encode (state, m) {
    c.uint8.encode(state, m.id)
    c.string.encode(state, m.name)
  },
  decode (state) {
    const r0 = c.uint8.decode(state)
    const r1 = c.string.decode(state)

    return {
      id: r0,
      name: r1
    }
  }
}

function setVersion (v) {
  version = v
}

function encode (name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode (name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum (name) {
  switch (name) {
    default: throw new Error('Enum not found ' + name)
  }
}

function getEncoding (name) {
  switch (name) {
    case '@hyperdb-example/user': return encoding0
    default: throw new Error('Encoder not found ' + name)
  }
}

function getStruct (name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode (state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode (state, m) {
      version = v
      enc.encode(state, m)
    },
    decode (state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
